#!/bin/sh

# cd to file containing script or something?
BASEDIR=$(dirname "$0")
echo "$BASEDIR"
cd "$BASEDIR"

mkdir -p "$HOME/Library/Application Support/Space Station 14"

ARCH=$(uname -m)

export DOTNET_ROOT="$(pwd)/../Resources/$ARCH/dotnet"

exec ../Resources/$ARCH/bin/SS14.Launcher "$@" > "$HOME/Library/Application Support/Space Station 14/launcher.log"
