#!/bin/bash

# cd to file containing script or something?
BASEDIR=$(dirname "$0")
echo "$BASEDIR"
cd "$BASEDIR"

LOADER_PATH="../Resources/$(uname -m)/bin/SS14.Loader"

if [[ -z ${SS14_LOG_CLIENT} ]]; then
    # No log path
    exec $LOADER_PATH "$@"
else
    exec $LOADER_PATH "$@" > "$SS14_LOG_CLIENT" 2>&1
fi

